---
- name: IBM i apply a set of single PTFs one by one
  hosts: ibmi
  gather_facts: no
  collections:
    - ibm.power_ibmi
  vars:
    to_be_applied_list:
      - {'ptf_id':'SI73543', 'product':'5770UME'}
      - {'ptf_id':'SI73430', 'product':'5733SC1'}

  tasks:
    - name: Wait 30 Mins before Update
      pause:
        seconds: 1800
        
    - name: apply a list of single ptfs
      include_role:
        name: apply_ptf
