---
- name: apply IBM i PTF update
  hosts: IBMi_nodes
  gather_facts: no
  collections:
    - ibm.power_ibmi
  tasks:
  
    - name: Wait 30 mins before apply
      pause:
        seconds: 1800
        
    - name: Install a single PTF
      ibm.power_ibmi.ibmi_fix:
        product_id: '5770DBM'
        save_file_object: 'QSI72223'
        save_file_lib: 'QGPL'
        delayed_option: "*NO"
        temp_or_perm: "*TEMP"
        operation: 'load_and_apply'
        fix_list:
          - "SI72223"
        become_user: "QSECOFR"
        become_user_password: "yourpassword"
    - name: query ptf
      ibm.power_ibmi.ibmi_fix:
        operation: 'query'
        fix_list:
          - "SI72223"
          - "SI70819"
