---
- name: Gather IBM i system info and display key values
  hosts: IBMi_nodes
  gather_facts: no
  collections:
    - ibm.power_ibmi


  tasks:
    - name: Collect IBM i system facts
      ibm.power_ibmi.ibmi_facts: 
      register: ibmi_facts_result

    - name: Show full fact result (for debugging)
      debug:
        var: ibmi_facts_result





